---
title: "Homework 3"
author: "Joe Diaz"
date: "9/10/2019"
output: html_document
---
### Question 5.1
**Using crime data from the file uscrime.txt (http://www.statsci.org/data/general/uscrime.txt,**
**description at http://www.statsci.org/data/general/uscrime.html), test to see whether there are any**
**outliers in the last column (number of crimes per 100,000 people). Use the grubbs.test function in**
**the outliers package in R.**

###Question 6.1
**Describe a situation or problem from your job, everyday life, current events, etc., for which a Change**
**Detection model would be appropriate. Applying the CUSUM technique, how would you choose the**
**critical value and the threshold?**

In the world of food supply chain, a change detection model would be beneficial in managning food packaging (i.e putting the correct amount of sauce in a packet). Since mostly machines do these sorts of tasks, a change would be detrimental to the business as it can result in wasted material, or too little of the product packaged. Since an unoticed changed

###Question 6.2
**1. Using July through October daily-high-temperature data for Atlanta for 1996 through 2015, use**
**a CUSUM approach to identify when unofficial summer ends (i.e., when the weather starts**
**cooling off) each year. You can get the data that you need from the file temps.txt or online,**
**for example at http://www.iweathernet.com/atlanta-weather-records or**
**https://www.wunderground.com/history/airport/KFTY/2015/7/1/CustomHistory.html . You can**
**use R if you’d like, but it’s straightforward enough that an Excel spreadsheet can easily do the**
**job too.**
**2. Use a CUSUM approach to make a judgment of whether Atlanta’s summer climate has gotten**
**warmer in that time (and if so, when).**